name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test (iOS)
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: List available simulators
        run: xcrun simctl list devices

      - name: Build project
        run: |
          xcodebuild clean build \
            -project CICD.xcodeproj \
            -scheme CICD \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Run unit tests
        run: |
          xcodebuild test \
            -project CICD.xcodeproj \
            -scheme CICD \
             -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
