name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test (iOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Xcode version to 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Install dependencies
        run: |
          brew install swiftlint || echo "SwiftLint already installed"
          pod install || echo "No Podfile found"

      - name: Build project
        run: |
          xcodebuild clean build \
            -project CICD.xcodeproj \
            -scheme CICD \
            -destination 'platform=iOS Simulator,name=Any iOS Simulator Device' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Run unit tests
        run: |
          xcodebuild test \
            -project CICD.xcodeproj \
            -scheme CICD \
            -destination 'platform=iOS Simulator,name=Any iOS Simulator Device' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
